services:
  gollery-server:
    build:
      context: .
    container_name: gollery-server
    image: gollery-server:latest
    environment:
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - ./.env
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - gollery_db
    networks:
      - gollery-network

  gollery_db:
    build:
      context: ./database
    container_name: gollery_db
    image: go_mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    restart: always
    networks:
      - gollery-network

networks:
  gollery-network:
