// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package photo

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Form() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<section class=\"min-w-80 flex flex-col flex-1 items-center justify-center h-full\"><form hx-post=\"/photos/add-new\" hx-encoding=\"multipart/form-data\" class=\"flex flex-col gap-8 p-4 bg-zinc-300 dark:bg-zinc-600 rounded-md shadow-md\"><div><label for=\"title\">Title</label> <input type=\"text\" name=\"title\" value=\"\" class=\"w-full\" required></div><div><label for=\"description\">Description</label> <textarea type=\"textarea\" name=\"description\" rows=\"6\" value=\"\" class=\"w-full\" required></textarea></div><input type=\"file\" name=\"file\" accept=\"image/jpeg\"> <button type=\"submit\" class=\"bg-zinc-700 text-zinc-200 dark:bg-zinc-200 dark:text-zinc-700 py-1 px-2 mt-2 rounded-md\">Send</button></form></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
