// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

import (
	"database/sql"
	"time"
)

type Photo struct {
	PhotoID     uint32
	UserID      uint32
	Title       string
	Description sql.NullString
	Filename    string
	Date        time.Time
}

type User struct {
	UserID   uint32
	Username string
	Email    string
	Password string
	CretedAt time.Time
}
